# Generated by Django 5.1.1 on 2024-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('toko', models.CharField(max_length=100)),
            ],
        ),
    ]
