# Generated by Django 5.1.2 on 2024-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyimpanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
