# Generated by Django 5.1.1 on 2024-10-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyimpanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='kategori',
            field=models.CharField(max_length=50),
        ),
    ]
