# Generated by Django 5.1.2 on 2024-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyimpanan', '0002_alter_katalog_harga_alter_katalog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='kategori',
            field=models.IntegerField(),
        ),
    ]
