# Generated by Django 5.1.2 on 2024-10-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penyimpanan', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
