# Generated by Django 5.1.2 on 2024-10-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('penyimpanan', '0002_alter_katalog_harga_alter_katalog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
