# Generated by Django 5.1.2 on 2024-11-24 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=100)),
                ('potongan', models.FloatField()),
                ('masa_berlaku', models.IntegerField()),
                ('minimal_transaksi', models.FloatField()),
                ('toko_terkait', models.JSONField(default=list)),
            ],
        ),
    ]
