# Generated by Django 5.1.2 on 2024-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=100)),
                ('potongan', models.FloatField()),
                ('masa_berlaku', models.IntegerField()),
                ('minimal_transaksi', models.FloatField()),
                ('toko_terkait', models.ManyToManyField(related_name='promos', to='promo.store')),
            ],
        ),
    ]
