# Generated by Django 5.1.2 on 2024-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='minimal_transaksi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='potongan',
            field=models.IntegerField(),
        ),
    ]
