# Generated by Django 5.1.2 on 2024-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promo_minimal_transaksi_alter_promo_potongan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='minimal_transaksi',
            field=models.FloatField(),
        ),
    ]
