# Generated by Django 5.1.1 on 2024-10-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_alter_promo_minimal_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='kode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='masa_berlaku',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='minimal_transaksi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='potongan',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='promo',
            name='toko_terkait',
        ),
        migrations.AddField(
            model_name='promo',
            name='toko_terkait',
            field=models.ManyToManyField(related_name='promos', to='promo.store'),
        ),
    ]
