# Generated by Django 5.1.2 on 2024-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_alter_promo_minimal_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='minimal_transaksi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='potongan',
            field=models.FloatField(),
        ),
    ]
