# Generated by Django 5.1 on 2024-10-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulasan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='ulasan_makanan_souvenir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulasan.katalog'),
        ),
    ]
