# Generated by Django 5.1 on 2024-10-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyimpanan', '0002_alter_katalog_harga_alter_katalog_id_and_more'),
        ('ulasan', '0002_katalog_alter_ulasan_ulasan_makanan_souvenir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulasan',
            name='ulasan_makanan_souvenir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyimpanan.katalog'),
        ),
        migrations.DeleteModel(
            name='Katalog',
        ),
    ]
