# Generated by Django 5.1 on 2024-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulasan', '0003_alter_ulasan_ulasan_makanan_souvenir_delete_katalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulasan',
            name='nama_makanan_souvenir',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
