# Generated by Django 5.1 on 2024-10-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulasan', '0004_ulasan_nama_makanan_souvenir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulasan',
            name='nama_makanan_souvenir',
        ),
    ]
