# Generated by Django 5.1.1 on 2024-10-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penyimpanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('e_wallet', 'E-Wallet'), ('ovo', 'OVO'), ('gopay', 'GoPay'), ('dana', 'Dana'), ('linkaja', 'LinkAja')], default='bank_transfer', max_length=50)),
                ('amount', models.IntegerField()),
                ('total_payment', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyimpanan.katalog')),
            ],
        ),
    ]
