# Generated by Django 5.1.1 on 2024-10-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
        ('penyimpanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('e_wallet', 'E-Wallet'), ('ovo', 'OVO'), ('gopay', 'GoPay'), ('dana', 'Dana'), ('linkaja', 'LinkAja')], default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyimpanan.katalog'),
        ),
    ]
