# Generated by Django 5.1.1 on 2024-10-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_produk_rename_payment_date_pembayaran_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='pembayaran.produk'),
        ),
    ]
