# Generated by Django 5.1.1 on 2024-10-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0003_alter_pembayaran_product'),
        ('penyimpanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='penyimpanan.katalog'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='payment_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
