# Generated by Django 5.1.1 on 2024-10-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0005_pembayaran_total_payment_alter_pembayaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(default='Success', max_length=20),
        ),
    ]
