# Generated by Django 5.1.1 on 2024-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0007_rename_total_payment_pembayaran_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
