# Generated by Django 5.1.1 on 2024-10-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0008_alter_pembayaran_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='total_payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('e_wallet', 'E-Wallet')], default='bank_transfer', max_length=50),
        ),
    ]
